[package]
name = "gibberish_dyn_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
gibberish_tree = { path = "../gibberish_tree" }
clap = { version = "4.5.53", features = ["derive"] }
libloading = "0.9.0"
